### ISSUE TITLE
Installation error with R 3.6

### ISSUE THREAD

**Issue by pkrog** [adelabriere/mineMS2#3]
When installing with R 3.6, I've met several errors with .Rd files. Here is one of them:
```
Error : (converted from warning) /tmp/Rtmp5ObdcG/R.INSTALL2c00352e6c52/mineMS2/man/findPatternsExplainingComponents.Rd:21: unexpected section header '\description'
ERROR: installing Rd objects failed for package ‘mineMS2’
```
In order to correct those mistakes, could you please add me as contributor. I'll then also be able to upgrade version tag in order to build a new version of the conda package for Galaxy.
CC: @ethevenot

**Comment by adelabriere** [comment]
It s fixed and I added you as a contributor.
